package com.mbt925.weatherapp.feature.api.models

enum class WeatherType {
    ClearSky,
    MainlyClear,
    PartlyCloudy,
    Overcast,
    Foggy,
    DepositingRimeFog,
    LightDrizzle,
    ModerateDrizzle,
    DenseDrizzle,
    LightFreezingDrizzle,
    DenseFreezingDrizzle,
    SlightRain,
    ModerateRain,
    HeavyRain,
    HeavyFreezingRain,
    SlightSnowFall,
    ModerateSnowFall,
    HeavySnowFall,
    SnowGrains,
    SlightRainShowers,
    ModerateRainShowers,
    ViolentRainShowers,
    SlightSnowShowers,
    HeavySnowShowers,
    ModerateThunderstorm,
    SlightHailThunderstorm,
    HeavyHailThunderstorm;
}
